// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKb4V5SvzIcXog3aRX3LjNAbSdeDxgV8',
    appId: '1:617079265736:web:36d91613a8be2817ec48fd',
    messagingSenderId: '617079265736',
    projectId: 'nowrin-store-1',
    authDomain: 'nowrin-store-1.firebaseapp.com',
    storageBucket: 'nowrin-store-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjb88ugEL9jJzxrEAbF2JWa7jTGRtEd60',
    appId: '1:617079265736:android:91a49a604545b518ec48fd',
    messagingSenderId: '617079265736',
    projectId: 'nowrin-store-1',
    storageBucket: 'nowrin-store-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1vN29NWSy9k_l3-n3lRp302oHXslgtNc',
    appId: '1:617079265736:ios:aaa8ea189d21bc4eec48fd',
    messagingSenderId: '617079265736',
    projectId: 'nowrin-store-1',
    storageBucket: 'nowrin-store-1.firebasestorage.app',
    iosBundleId: 'com.example.productCartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1vN29NWSy9k_l3-n3lRp302oHXslgtNc',
    appId: '1:617079265736:ios:aaa8ea189d21bc4eec48fd',
    messagingSenderId: '617079265736',
    projectId: 'nowrin-store-1',
    storageBucket: 'nowrin-store-1.firebasestorage.app',
    iosBundleId: 'com.example.productCartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKKb4V5SvzIcXog3aRX3LjNAbSdeDxgV8',
    appId: '1:617079265736:web:a0fcabf9cb2f8663ec48fd',
    messagingSenderId: '617079265736',
    projectId: 'nowrin-store-1',
    authDomain: 'nowrin-store-1.firebaseapp.com',
    storageBucket: 'nowrin-store-1.firebasestorage.app',
  );
}
